server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.65.66 # Redis?????
    database: 0 # Redis?????????0?
    port: 6379 # Redis???????
    password: # Redis?????????????
    timeout: 3000ms # ??????????

logging:
  level:
    root: info
    com.tulingxueyuan: debug

aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com # oss?????????
    accessKeyId: LTAI4GHWCM5LdNoiLy35mBog # ?????????????
    accessKeySecret: Vytl0LAIKGmiWATIuuwevN3LjzQs9S # ????????????oss????????????
    bucketName: tulingmall-xushu # oss?????
    policy:
      expire: 300 # ?????(S)
    maxSize: 10 # ??????(M)
    #callback:  # ????????????
    dir:
      prefix: tulingmall/images/ # ?????????